name: Build datadog-agent

on: push

jobs:
  build:
    strategy:
      matrix:
        distribution:
          - debian
        include:
          - distribution: debian
            platforms: linux/arm/v7
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Clone datadog-agent-buildimages
        run: |
          git clone https://github.com/DataDog/datadog-agent-buildimages
          mv ./Dockerfile ./datadog-agent-buildimages
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./datadog-agent-buildimages
          platforms: ${{ matrix.platforms }}
          tags: ${{ github.repository }}
          build-args: |
            DISTRIBUTION=${{ matrix.distribution }}
          push: true
